apiVersion: v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-cronjob-container
              image: my-cronjob-image
              command: ["my-cronjob-command"]
          restartPolicy: OnFailure

