apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: example-container
      image: your-container-image
      env:
        - name: ENV_VAR_1
          valueFrom:
            secretKeyRef:
              name: secret-example
              key: ENV_VAR_1
        - name: ENV_VAR_2
          valueFrom:
            secretKeyRef:
              name: secret-example
              key: ENV_VAR_2
        - name: ENV_VAR_3
          valueFrom:
            secretKeyRef:
              name: secret-example
              key: ENV_VAR_3

