---
apiVersion: v1
kind: Secret
metadata:
  name: secret-example
type: Opaque
data:
  ENV_VAR_1: <base64-encoded-value-1>
  ENV_VAR_2: <base64-encoded-value-2>
  ENV_VAR_3: <base64-encoded-value-3>
  ...
---

apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: example-container
      image: your-container-image
      env:
        - name: ENV_VAR_1
          valueFrom:
            secretKeyRef:
              name: secret-example
              key: ENV_VAR_1
        - name: ENV_VAR_2
          valueFrom:
            secretKeyRef:
              name: secret-example
              key: ENV_VAR_2
        - name: ENV_VAR_3
          valueFrom:
            secretKeyRef:
              name: secret-example
              key: ENV_VAR_3
---

