apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: example-image
    volumeMounts:
    - name: example-volume
      mountPath: /path/to/mount
  volumes:
  - name: example-volume
    emptyDir: {}

